name: osmtogeojson
description: "Converts OSM data (XML or Overpass JSON) to GeoJSON FeatureCollections."
version: 0.1.0
homepage: https://github.com/domyd/osmtogeojson-dart
topics:
  - geojson
  - openstreetmap
  - map

environment:
  sdk: ^3.12.0

dependencies:
  xml: ^7.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.1.0
  checks: ^0.3.1
